Merge change 010
astuff/pacmod_dbc pull request #43
Opened 2019-07-11 21:37 UTC by asaxsma

This is the item we conditionally approved at change 009 meeting.  We finally approved it online.  Calling this change 010.

2019-07-12 14:59 UTC, JWhitleyAStuff commented on as_pacmod.dbc
> + SG_ XBR_CONTROL_MODE : 29|2@0+ (1,0) [0|2] ""  PACMOD
I thought the final decision was to split up the DECCEL_CMD and the XBR bits into a _CMD and an _AUX_CMD? Did I misunderstand the outcome?

2019-07-12 14:59 UTC, JWhitleyWork requested changes
See comment on DECCEL_CMD message.

2019-07-12 18:58 UTC, asaxsma commented
I was thinking we came down on the side of combining them.  It avoided having to invent this new "aux_command".  Does anyone else remember where we came down at?

2019-07-12 19:02 UTC, asaxsma commented
Here's what I remember about the conversation:
Pro for combining them: didn't need to invent new message, coupling with deccel command is pretty tight.
Pro for separating them: didn't have to violate existing cmd message architecture (like steering does).

2019-07-12 23:07 UTC, mlemm99 commented
I remember combining them because they are so dependant. The mode dictates if the Accel command is accepted

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Andy <notifications@github.com>
Sent: Friday, July 12, 2019 2:02:51 PM
To: astuff/pacmod_dbc
Cc: Michael Lemm; Review requested
Subject: Re: [astuff/pacmod_dbc] Merge change 010 (#43)


Here's what I remember about the conversation:
Pro for combining them: didn't need to invent new message, coupling with deccel command is pretty tight.
Pro for separating them: didn't have to violate existing cmd message architecture (like steering does).

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub<https://github.com/astuff/pacmod_dbc/pull/43?email_source=notifications&email_token=AID6NKRR22AGCBLZOCC5RETP7DINXA5CNFSM4IBV5SOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZ2TPDQ#issuecomment-510998414>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AID6NKTXQALP5QOCHXE6SNDP7DINXANCNFSM4IBV5SOA>.

2019-07-12 23:16 UTC, JWhitleyAStuff commented
I think Mike might be right. LGTM.

2019-07-12 23:16 UTC, JWhitleyWork submitted a review, later dismissed

2019-07-12 23:37 UTC, mlemm99 commented
LGTM = Let's Get To Merging

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Joshua Whitley <notifications@github.com>
Sent: Friday, July 12, 2019 6:16:47 PM
To: astuff/pacmod_dbc
Cc: Michael Lemm; Review requested
Subject: Re: [astuff/pacmod_dbc] Merge change 010 (#43)


@JWhitleyAStuff approved this pull request.

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub<https://github.com/astuff/pacmod_dbc/pull/43?email_source=notifications&email_token=AID6NKSI3SLLMBRTBGLC72TP7EGF7A5CNFSM4IBV5SOKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB6LETJQ#pullrequestreview-261507494>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AID6NKRO6X6NGU3DXPIJQXLP7EGF7ANCNFSM4IBV5SOA>.

2019-07-15 13:19 UTC, driscoll85 submitted a review, later dismissed

2019-07-17 13:51 UTC, mlemm99 approved these changes

2019-07-17 15:25 UTC, driscoll85 approved these changes

2019-07-17 16:08 UTC, JWhitleyWork approved these changes

2019-07-17 16:09 UTC, merged