Rightsize DLCs.
astuff/pacmod_dbc pull request #52
Opened 2019-08-15 15:08 UTC by asaxsma

2019-08-15 15:11 UTC, mlemm99 submitted a review, later dismissed

2019-08-16 20:38 UTC, JWhitleyWork requested changes

2019-08-16 20:38 UTC, JWhitleyAStuff commented on as_pacmod.ini
> +[View_Vehicles]
I don't believe this file should be in the repo.

2019-08-19 13:33 UTC, mlemm99 approved these changes

2019-08-19 13:39 UTC, driscoll85 approved these changes

2019-08-19 22:05 UTC, JWhitleyWork approved these changes

2019-08-20 13:11 UTC, merged